/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daftarmahasiswa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private Boolean isUpdate = false;
    private int selectedID = -1;
    private ArrayList<Mahasiswa> listMhs;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        listMhs = new ArrayList<>();
        //Dummy
        listMhs.add(new Mahasiswa("1111", "Aaaa", "A"));
        listMhs.add(new Mahasiswa("2222", "Bbbb", "B"));
        listMhs.add(new Mahasiswa("3333", "Cccc", "C"));
        // Set Table
        table_data.setModel(setTable());
        // Hide Delete button
        button_delete.setVisible(false);
    }

    public final DefaultTableModel setTable() {
        Object[] column = {"NIM", "Nama", "Nilai"};
        DefaultTableModel dataTabel = new DefaultTableModel(null, column);
        for (int i = 0; i < listMhs.size(); i++) {
            Object[] row = new Object[3];
            row[0] = listMhs.get(i).getNim();
            row[1] = listMhs.get(i).getNama();
            row[2] = listMhs.get(i).getNilai();
            dataTabel.addRow(row);
        }
        return dataTabel;
    }

    public void insertData() {
        if(text_nim.getText().equals("")){
            JOptionPane.showMessageDialog(null, "NIM Tidak Boleh Kosong!");
        }else if(text_nama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong!");
        }else if(text_nilai.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nilai Tidak Boleh Kosong!");
        }else {
            // Get Data
            String nim = text_nim.getText();
            String nama = text_nama.getText();
            String nilai = text_nilai.getText();
            //Update Table
            listMhs.add(new Mahasiswa(nim, nama, nilai));
            table_data.setModel(setTable());
            
            System.out.println("Insert Success!");
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
        }
        // mengosongkan label
        text_nim.setText("");
        text_nama.setText("");
        text_nilai.setText("");
    }

    public void updateData() {
        // Get Data
        String nim = text_nim.getText();
        String nama = text_nama.getText();
        String nilai = text_nilai.getText();
        //System.out.println(nim + nama + nilai);

        listMhs.get(selectedID).setNim(nim);
        listMhs.get(selectedID).setNama(nama);
        listMhs.get(selectedID).setNilai(nilai);
           
        table_data.setModel(setTable());
        
        System.out.println("Update Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
     
        // mengosongkan label
        text_nim.setText("");
        text_nama.setText("");
        text_nilai.setText("");
    }

    public void deleteData() {
        int row = table_data.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)table_data.getModel();
        model.removeRow(row);
        System.out.println("Delete Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        // mengosongkan label
        text_nim.setText("");
        text_nama.setText("");
        text_nilai.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_project = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        button_add = new javax.swing.JButton();
        text_nim = new javax.swing.JTextField();
        label_nim = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        label_nilai = new javax.swing.JLabel();
        text_nilai = new javax.swing.JTextField();
        scrollpanel_project = new javax.swing.JScrollPane();
        table_data = new javax.swing.JTable();
        button_delete = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_title.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("Data Mahasiswa");

        button_add.setFont(new java.awt.Font("Schadow BT", 0, 14)); // NOI18N
        button_add.setText("Add Data");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        text_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nimActionPerformed(evt);
            }
        });

        label_nim.setFont(new java.awt.Font("Schadow BT", 0, 14)); // NOI18N
        label_nim.setText("Masukkan NIM");

        label_nama.setFont(new java.awt.Font("Schadow BT", 0, 14)); // NOI18N
        label_nama.setText("Masukkan Nama");

        text_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_namaActionPerformed(evt);
            }
        });

        label_nilai.setFont(new java.awt.Font("Schadow BT", 0, 14)); // NOI18N
        label_nilai.setText("Masukkan Nilai");

        text_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nilaiActionPerformed(evt);
            }
        });

        table_data.setAutoCreateRowSorter(true);
        table_data.setFont(new java.awt.Font("Schadow BT", 0, 14)); // NOI18N
        table_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_data.setToolTipText("");
        table_data.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_data.setUpdateSelectionOnSort(false);
        table_data.setVerifyInputWhenFocusTarget(false);
        table_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dataMouseClicked(evt);
            }
        });
        scrollpanel_project.setViewportView(table_data);

        button_delete.setFont(new java.awt.Font("Schadow BT", 0, 14)); // NOI18N
        button_delete.setText("Delete Data");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_cancel.setFont(new java.awt.Font("Schadow BT", 0, 14)); // NOI18N
        button_cancel.setText("Cancel Data");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_projectLayout = new javax.swing.GroupLayout(panel_project);
        panel_project.setLayout(panel_projectLayout);
        panel_projectLayout.setHorizontalGroup(
            panel_projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_projectLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(label_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_projectLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(panel_projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollpanel_project)
                    .addGroup(panel_projectLayout.createSequentialGroup()
                        .addGroup(panel_projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_projectLayout.createSequentialGroup()
                                .addGroup(panel_projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nim)
                                    .addComponent(label_nama))
                                .addGap(31, 31, 31))
                            .addGroup(panel_projectLayout.createSequentialGroup()
                                .addComponent(label_nilai)
                                .addGap(37, 37, 37)))
                        .addGroup(panel_projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(panel_projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_cancel)
                            .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panel_projectLayout.setVerticalGroup(
            panel_projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_projectLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label_title)
                .addGap(28, 28, 28)
                .addGroup(panel_projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim)
                    .addComponent(button_add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama)
                    .addComponent(button_cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nilai)
                    .addComponent(button_delete))
                .addGap(42, 42, 42)
                .addComponent(scrollpanel_project, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_project, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_project, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nimActionPerformed

    private void text_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_namaActionPerformed

    private void text_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nilaiActionPerformed

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        // TODO add your handling code here:
        if (isUpdate == false)
            insertData();
        else {
            updateData();
            button_add.setText("Add");
            button_delete.setVisible(false);
            this.isUpdate = false;
        }
    }//GEN-LAST:event_button_addActionPerformed

    private void table_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dataMouseClicked
        // TODO add your handling code here:
        this.isUpdate = true;

        //Get Selected Data
        int row = table_data.getSelectedRow();
        String selectedNim = (table_data.getModel().getValueAt(row, 0).toString());
        String selectedNama = (table_data.getModel().getValueAt(row, 1).toString());
        String selectedNilai = (table_data.getModel().getValueAt(row, 2).toString());

        for (int i = 0; i < listMhs.size(); i++) {
            if (selectedNim.equals(listMhs.get(i).getNim())) {
                selectedID = i;
                break;
            }
        }

        //System.out.println(selectedID);
        text_nim.setText(selectedNim);
        text_nama.setText(selectedNama);
        text_nilai.setText(selectedNilai);

        button_add.setText("Update");
        button_delete.setVisible(true);
    }//GEN-LAST:event_table_dataMouseClicked

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:
        if (isUpdate == true) {
            deleteData();
            button_add.setText("Add");
            button_delete.setVisible(false);
            this.isUpdate = false;
        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        // TODO add your handling code here:
        text_nim.setText("");
        text_nama.setText("");
        text_nilai.setText("");
        button_add.setText("Add");
        button_delete.setVisible(false);
        this.isUpdate = false;
    }//GEN-LAST:event_button_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_delete;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nilai;
    private javax.swing.JLabel label_nim;
    private javax.swing.JLabel label_title;
    private javax.swing.JPanel panel_project;
    private javax.swing.JScrollPane scrollpanel_project;
    private javax.swing.JTable table_data;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_nilai;
    private javax.swing.JTextField text_nim;
    // End of variables declaration//GEN-END:variables
}
